capability_extractor_agent_node:
  ros__parameters:
    urdf_path: "/home/pofe/planning_ws/bringup/urdf/unitree_h1.urdf"
    out_yaml_path: "/home/pofe/planning_ws/bringup/semantic/unitree_h1_semantic.yaml"


domain_file_generator_node:
  ros__parameters:
    #backend: "ollama"
    #ollama_model: "qwen3.5:latest"
    backend: openai
    output_file: "/home/pofe/planning_ws/bringup/athena_domain.pddl"

