bt_planner:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: 'planning_w_execution.xml'
    plugin_lib_names:
    - nav2_recovery_node_bt_node
    - plan2_compute_plan_action_bt_node
    - plan2_is_action_condition_bt_node



task_planner_server:
 ros__parameters:
    use_sim_time: True
    planner_frequency: 3.0
    planner_plugins: ["MetricFF"]
    MetricFF:
      plugin: "plan2_planner::MetricFF"