bt_planner:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_plan_bt_xml: 'planning_w_execution_hddl.xml'
    plugin_lib_names:
    - nav2_recovery_node_bt_node
    - nav2_rate_controller_bt_node
    - plan2_noop_action_bt_node
    - plan2_compute_plan_action_bt_node
    - plan2_is_action_condition_bt_node
    - plan2_send_move_action_bt_node
    - plan2_dispatch_tasks_action_bt_node
    - plan2_execute_plan_node_bt_node

task_planner_server:
 ros__parameters:
    use_sim_time: True
    planner_frequency: 3.0
    planner_plugins: ["MetricFF", "LPG", "TFD", "Lilotane"]
    MetricFF:
      plugin: "plan2_planner::MetricFF"
      problem_type: "Symbolic"
      output_name: "plan.pddl"
      definition:
        robot: "machine"
        location: "location"
      plan_type: "PARTIAL_ORDERED"
    LPG:
      plugin: "plan2_planner::LPG"
      problem_type: "Symbolic"
      output_name: "plan.pddl"
      definition:
        robot: "machine"
        location: "location"
      plan_type: "PARTIAL_ORDERED"
    TFD:
      plugin: "plan2_planner::TFD"
      problem_type: "Symbolic"
      output_name: "plan.hddl"
      definition:
        robot: "vehicle"
        location: "location"
      plan_type: "PARTIAL_ORDERED"
    Lilotane:
      plugin: "plan2_planner::Lilotane"
      problem_type: "Symbolic"
      output_name: "plan.hddl"
      definition:
        robot: "vehicle"
        location: "location"
      plan_type: "PARTIAL_ORDERED"