bt_planner:
  ros__parameters:
    groot_port: 1668
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    bt_package_dir: 'athena_behavior_tree'
    default_plan_bt_xml: 'planning_w_dispatching_hddl.xml'
    #default_plan_bt_xml: 'generate_problem_file.xml'
    #default_plan_bt_xml: 'plan_computation_w_planning_and_dispatching.xml'
    plugin_lib_names:
    - athena_recovery_node_bt_node
    - athena_rate_controller_bt_node
    - athena_compute_plan_action_bt_node
    - athena_execute_plan_node_bt_node
    - athena_dispatch_methods_action_bt_node
    - athena_selected_robot_controller_bt_node
    - athena_send_method_action_bt_node
    - athena_dispatch_tasks_action_bt_node
    - athena_send_action_action_bt_node
    - athena_update_state_action_bt_node
    - athena_generate_problem_file_action_bt_node
    - athena_update_prompt_action_bt_node
    - athena_detect_objects_action_bt_node
    - athena_updated_prompt_controller_bt_node
    - athena_pipeline_sequence_bt_node
    - athena_all_object_detected_condition_node
    - athena_check_problem_file_condition_node

task_planner_server:
 ros__parameters:
    use_sim_time: True
    planner_frequency: 3.0
    definitions:
      robot: "robot"
      location: "location"
      plan_filename: "plan.hddl"
      proto_filename: "ExePlan.data"
    planner_plugins: ["MetricFF", "LPG", "TFD", "Lilotane"]
    MetricFF:
      plugin: "athena_planner::MetricFF"
    LPG:
      plugin: "athena_planner::LPG"
      plan_type: "PARTIAL_ORDERED"
    TFD:
      plugin: "athena_planner::TFD"
    Lilotane:
      plugin: "athena_planner::Lilotane"

state_updater_server:
  ros__parameters:
      use_sim_time: True
      planner_frequency: 3.0
      planner_plugins: ["SimpleStateUpdater"]
      SimpleStateUpdater:
        plugin: "athena_planner::SimpleStateUpdater"