// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: executionplan.proto
// Protobuf C++ Version: 6.31.1

#ifndef executionplan_2eproto_2epb_2eh
#define executionplan_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_executionplan_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_executionplan_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_executionplan_2eproto;
}  // extern "C"
namespace athena {
class ProtoAction;
struct ProtoActionDefaultTypeInternal;
extern ProtoActionDefaultTypeInternal _ProtoAction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProtoAction_class_data_;
class ProtoExecutionPlan;
struct ProtoExecutionPlanDefaultTypeInternal;
extern ProtoExecutionPlanDefaultTypeInternal _ProtoExecutionPlan_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProtoExecutionPlan_class_data_;
class ProtoMethod;
struct ProtoMethodDefaultTypeInternal;
extern ProtoMethodDefaultTypeInternal _ProtoMethod_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProtoMethod_class_data_;
class ProtoProblem;
struct ProtoProblemDefaultTypeInternal;
extern ProtoProblemDefaultTypeInternal _ProtoProblem_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProtoProblem_class_data_;
}  // namespace athena
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace athena {

// ===================================================================


// -------------------------------------------------------------------

class ProtoProblem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:athena.ProtoProblem) */ {
 public:
  inline ProtoProblem() : ProtoProblem(nullptr) {}
  ~ProtoProblem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProtoProblem* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProtoProblem));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtoProblem(::google::protobuf::internal::ConstantInitialized);

  inline ProtoProblem(const ProtoProblem& from) : ProtoProblem(nullptr, from) {}
  inline ProtoProblem(ProtoProblem&& from) noexcept
      : ProtoProblem(nullptr, ::std::move(from)) {}
  inline ProtoProblem& operator=(const ProtoProblem& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtoProblem& operator=(ProtoProblem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtoProblem& default_instance() {
    return *reinterpret_cast<const ProtoProblem*>(
        &_ProtoProblem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ProtoProblem& a, ProtoProblem& b) { a.Swap(&b); }
  inline void Swap(ProtoProblem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtoProblem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtoProblem* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProtoProblem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtoProblem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtoProblem& from) { ProtoProblem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProtoProblem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "athena.ProtoProblem"; }

 protected:
  explicit ProtoProblem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ProtoProblem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ProtoProblem& from);
  ProtoProblem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ProtoProblem&& from) noexcept
      : ProtoProblem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDomainFieldNumber = 1,
    kProblemFieldNumber = 2,
  };
  // string domain = 1;
  void clear_domain() ;
  const ::std::string& domain() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_domain(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_domain();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_domain();
  void set_allocated_domain(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_domain() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_domain(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_domain();

  public:
  // string problem = 2;
  void clear_problem() ;
  const ::std::string& problem() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_problem(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_problem();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_problem();
  void set_allocated_problem(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_problem() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_problem(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_problem();

  public:
  // @@protoc_insertion_point(class_scope:athena.ProtoProblem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ProtoProblem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr domain_;
    ::google::protobuf::internal::ArenaStringPtr problem_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_executionplan_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProtoProblem_class_data_;
// -------------------------------------------------------------------

class ProtoMethod final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:athena.ProtoMethod) */ {
 public:
  inline ProtoMethod() : ProtoMethod(nullptr) {}
  ~ProtoMethod() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProtoMethod* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProtoMethod));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtoMethod(::google::protobuf::internal::ConstantInitialized);

  inline ProtoMethod(const ProtoMethod& from) : ProtoMethod(nullptr, from) {}
  inline ProtoMethod(ProtoMethod&& from) noexcept
      : ProtoMethod(nullptr, ::std::move(from)) {}
  inline ProtoMethod& operator=(const ProtoMethod& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtoMethod& operator=(ProtoMethod&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtoMethod& default_instance() {
    return *reinterpret_cast<const ProtoMethod*>(
        &_ProtoMethod_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ProtoMethod& a, ProtoMethod& b) { a.Swap(&b); }
  inline void Swap(ProtoMethod* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtoMethod* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtoMethod* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProtoMethod>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtoMethod& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtoMethod& from) { ProtoMethod::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProtoMethod* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "athena.ProtoMethod"; }

 protected:
  explicit ProtoMethod(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ProtoMethod(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ProtoMethod& from);
  ProtoMethod(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ProtoMethod&& from) noexcept
      : ProtoMethod(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParentsFieldNumber = 4,
    kActionsIdsFieldNumber = 5,
    kNameFieldNumber = 1,
    kRobotFieldNumber = 3,
    kIdFieldNumber = 2,
  };
  // repeated int32 parents = 4;
  int parents_size() const;
  private:
  int _internal_parents_size() const;

  public:
  void clear_parents() ;
  ::int32_t parents(int index) const;
  void set_parents(int index, ::int32_t value);
  void add_parents(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& parents() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_parents();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_parents() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_parents();

  public:
  // repeated int32 actions_ids = 5;
  int actions_ids_size() const;
  private:
  int _internal_actions_ids_size() const;

  public:
  void clear_actions_ids() ;
  ::int32_t actions_ids(int index) const;
  void set_actions_ids(int index, ::int32_t value);
  void add_actions_ids(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& actions_ids() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_actions_ids();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_actions_ids() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_actions_ids();

  public:
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string robot = 3;
  void clear_robot() ;
  const ::std::string& robot() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_robot(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_robot();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_robot();
  void set_allocated_robot(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_robot() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_robot(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_robot();

  public:
  // int32 id = 2;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:athena.ProtoMethod)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ProtoMethod& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> parents_;
    ::google::protobuf::internal::CachedSize _parents_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int32_t> actions_ids_;
    ::google::protobuf::internal::CachedSize _actions_ids_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr robot_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_executionplan_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProtoMethod_class_data_;
// -------------------------------------------------------------------

class ProtoAction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:athena.ProtoAction) */ {
 public:
  inline ProtoAction() : ProtoAction(nullptr) {}
  ~ProtoAction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProtoAction* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProtoAction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtoAction(::google::protobuf::internal::ConstantInitialized);

  inline ProtoAction(const ProtoAction& from) : ProtoAction(nullptr, from) {}
  inline ProtoAction(ProtoAction&& from) noexcept
      : ProtoAction(nullptr, ::std::move(from)) {}
  inline ProtoAction& operator=(const ProtoAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtoAction& operator=(ProtoAction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtoAction& default_instance() {
    return *reinterpret_cast<const ProtoAction*>(
        &_ProtoAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ProtoAction& a, ProtoAction& b) { a.Swap(&b); }
  inline void Swap(ProtoAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtoAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtoAction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProtoAction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtoAction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtoAction& from) { ProtoAction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProtoAction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "athena.ProtoAction"; }

 protected:
  explicit ProtoAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ProtoAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ProtoAction& from);
  ProtoAction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ProtoAction&& from) noexcept
      : ProtoAction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWaypointsFieldNumber = 4,
    kParentsFieldNumber = 6,
    kPreconditionsFieldNumber = 7,
    kEffectsFieldNumber = 8,
    kNameFieldNumber = 1,
    kRobotFieldNumber = 3,
    kMaterialFieldNumber = 5,
    kIdFieldNumber = 2,
  };
  // repeated string waypoints = 4;
  int waypoints_size() const;
  private:
  int _internal_waypoints_size() const;

  public:
  void clear_waypoints() ;
  const ::std::string& waypoints(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_waypoints(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_waypoints(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_waypoints();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_waypoints(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& waypoints() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_waypoints();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_waypoints() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_waypoints();

  public:
  // repeated int32 parents = 6;
  int parents_size() const;
  private:
  int _internal_parents_size() const;

  public:
  void clear_parents() ;
  ::int32_t parents(int index) const;
  void set_parents(int index, ::int32_t value);
  void add_parents(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& parents() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_parents();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_parents() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_parents();

  public:
  // repeated string preconditions = 7;
  int preconditions_size() const;
  private:
  int _internal_preconditions_size() const;

  public:
  void clear_preconditions() ;
  const ::std::string& preconditions(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_preconditions(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_preconditions(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_preconditions();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_preconditions(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& preconditions() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_preconditions();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_preconditions() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_preconditions();

  public:
  // repeated string effects = 8;
  int effects_size() const;
  private:
  int _internal_effects_size() const;

  public:
  void clear_effects() ;
  const ::std::string& effects(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_effects(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_effects(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_effects();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_effects(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& effects() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_effects();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_effects() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_effects();

  public:
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string robot = 3;
  void clear_robot() ;
  const ::std::string& robot() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_robot(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_robot();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_robot();
  void set_allocated_robot(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_robot() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_robot(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_robot();

  public:
  // string material = 5;
  void clear_material() ;
  const ::std::string& material() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_material(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_material();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_material();
  void set_allocated_material(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_material() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_material(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_material();

  public:
  // int32 id = 2;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:athena.ProtoAction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 81,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ProtoAction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> waypoints_;
    ::google::protobuf::RepeatedField<::int32_t> parents_;
    ::google::protobuf::internal::CachedSize _parents_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> preconditions_;
    ::google::protobuf::RepeatedPtrField<::std::string> effects_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr robot_;
    ::google::protobuf::internal::ArenaStringPtr material_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_executionplan_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProtoAction_class_data_;
// -------------------------------------------------------------------

class ProtoExecutionPlan final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:athena.ProtoExecutionPlan) */ {
 public:
  inline ProtoExecutionPlan() : ProtoExecutionPlan(nullptr) {}
  ~ProtoExecutionPlan() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProtoExecutionPlan* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProtoExecutionPlan));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtoExecutionPlan(::google::protobuf::internal::ConstantInitialized);

  inline ProtoExecutionPlan(const ProtoExecutionPlan& from) : ProtoExecutionPlan(nullptr, from) {}
  inline ProtoExecutionPlan(ProtoExecutionPlan&& from) noexcept
      : ProtoExecutionPlan(nullptr, ::std::move(from)) {}
  inline ProtoExecutionPlan& operator=(const ProtoExecutionPlan& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtoExecutionPlan& operator=(ProtoExecutionPlan&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtoExecutionPlan& default_instance() {
    return *reinterpret_cast<const ProtoExecutionPlan*>(
        &_ProtoExecutionPlan_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ProtoExecutionPlan& a, ProtoExecutionPlan& b) { a.Swap(&b); }
  inline void Swap(ProtoExecutionPlan* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtoExecutionPlan* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtoExecutionPlan* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProtoExecutionPlan>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtoExecutionPlan& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtoExecutionPlan& from) { ProtoExecutionPlan::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProtoExecutionPlan* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "athena.ProtoExecutionPlan"; }

 protected:
  explicit ProtoExecutionPlan(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ProtoExecutionPlan(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ProtoExecutionPlan& from);
  ProtoExecutionPlan(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ProtoExecutionPlan&& from) noexcept
      : ProtoExecutionPlan(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kActionFieldNumber = 1,
    kMethodFieldNumber = 2,
  };
  // repeated .athena.ProtoAction action = 1;
  int action_size() const;
  private:
  int _internal_action_size() const;

  public:
  void clear_action() ;
  ::athena::ProtoAction* PROTOBUF_NONNULL mutable_action(int index);
  ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>* PROTOBUF_NONNULL mutable_action();

  private:
  const ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>& _internal_action() const;
  ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>* PROTOBUF_NONNULL _internal_mutable_action();
  public:
  const ::athena::ProtoAction& action(int index) const;
  ::athena::ProtoAction* PROTOBUF_NONNULL add_action();
  const ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>& action() const;
  // repeated .athena.ProtoMethod method = 2;
  int method_size() const;
  private:
  int _internal_method_size() const;

  public:
  void clear_method() ;
  ::athena::ProtoMethod* PROTOBUF_NONNULL mutable_method(int index);
  ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>* PROTOBUF_NONNULL mutable_method();

  private:
  const ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>& _internal_method() const;
  ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>* PROTOBUF_NONNULL _internal_mutable_method();
  public:
  const ::athena::ProtoMethod& method(int index) const;
  ::athena::ProtoMethod* PROTOBUF_NONNULL add_method();
  const ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>& method() const;
  // @@protoc_insertion_point(class_scope:athena.ProtoExecutionPlan)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ProtoExecutionPlan& from_msg);
    ::google::protobuf::RepeatedPtrField< ::athena::ProtoAction > action_;
    ::google::protobuf::RepeatedPtrField< ::athena::ProtoMethod > method_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_executionplan_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProtoExecutionPlan_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProtoProblem

// string domain = 1;
inline void ProtoProblem::clear_domain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.domain_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ProtoProblem::domain() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoProblem.domain)
  return _internal_domain();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoProblem::set_domain(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.domain_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoProblem.domain)
}
inline ::std::string* PROTOBUF_NONNULL ProtoProblem::mutable_domain()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_domain();
  // @@protoc_insertion_point(field_mutable:athena.ProtoProblem.domain)
  return _s;
}
inline const ::std::string& ProtoProblem::_internal_domain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.domain_.Get();
}
inline void ProtoProblem::_internal_set_domain(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.domain_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoProblem::_internal_mutable_domain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.domain_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoProblem::release_domain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoProblem.domain)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.domain_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.domain_.Set("", GetArena());
  }
  return released;
}
inline void ProtoProblem::set_allocated_domain(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.domain_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.domain_.IsDefault()) {
    _impl_.domain_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoProblem.domain)
}

// string problem = 2;
inline void ProtoProblem::clear_problem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.problem_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& ProtoProblem::problem() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoProblem.problem)
  return _internal_problem();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoProblem::set_problem(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.problem_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoProblem.problem)
}
inline ::std::string* PROTOBUF_NONNULL ProtoProblem::mutable_problem()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_problem();
  // @@protoc_insertion_point(field_mutable:athena.ProtoProblem.problem)
  return _s;
}
inline const ::std::string& ProtoProblem::_internal_problem() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.problem_.Get();
}
inline void ProtoProblem::_internal_set_problem(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.problem_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoProblem::_internal_mutable_problem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.problem_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoProblem::release_problem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoProblem.problem)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.problem_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.problem_.Set("", GetArena());
  }
  return released;
}
inline void ProtoProblem::set_allocated_problem(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.problem_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.problem_.IsDefault()) {
    _impl_.problem_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoProblem.problem)
}

// -------------------------------------------------------------------

// ProtoAction

// string name = 1;
inline void ProtoAction::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ProtoAction::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoAction::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoAction.name)
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:athena.ProtoAction.name)
  return _s;
}
inline const ::std::string& ProtoAction::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void ProtoAction::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoAction::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoAction.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void ProtoAction::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoAction.name)
}

// int32 id = 2;
inline void ProtoAction::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t ProtoAction::id() const {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.id)
  return _internal_id();
}
inline void ProtoAction::set_id(::int32_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:athena.ProtoAction.id)
}
inline ::int32_t ProtoAction::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void ProtoAction::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string robot = 3;
inline void ProtoAction::clear_robot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& ProtoAction::robot() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.robot)
  return _internal_robot();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoAction::set_robot(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.robot_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoAction.robot)
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::mutable_robot()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_robot();
  // @@protoc_insertion_point(field_mutable:athena.ProtoAction.robot)
  return _s;
}
inline const ::std::string& ProtoAction::_internal_robot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.robot_.Get();
}
inline void ProtoAction::_internal_set_robot(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.robot_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::_internal_mutable_robot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.robot_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoAction::release_robot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoAction.robot)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.robot_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.robot_.Set("", GetArena());
  }
  return released;
}
inline void ProtoAction::set_allocated_robot(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.robot_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.robot_.IsDefault()) {
    _impl_.robot_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoAction.robot)
}

// repeated string waypoints = 4;
inline int ProtoAction::_internal_waypoints_size() const {
  return _internal_waypoints().size();
}
inline int ProtoAction::waypoints_size() const {
  return _internal_waypoints_size();
}
inline void ProtoAction::clear_waypoints() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.waypoints_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::add_waypoints()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_waypoints()->Add();
  // @@protoc_insertion_point(field_add_mutable:athena.ProtoAction.waypoints)
  return _s;
}
inline const ::std::string& ProtoAction::waypoints(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.waypoints)
  return _internal_waypoints().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::mutable_waypoints(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:athena.ProtoAction.waypoints)
  return _internal_mutable_waypoints()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ProtoAction::set_waypoints(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_waypoints()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:athena.ProtoAction.waypoints)
}
template <typename Arg_, typename... Args_>
inline void ProtoAction::add_waypoints(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_waypoints(),
                               ::std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:athena.ProtoAction.waypoints)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& ProtoAction::waypoints()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoAction.waypoints)
  return _internal_waypoints();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ProtoAction::mutable_waypoints() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoAction.waypoints)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_waypoints();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
ProtoAction::_internal_waypoints() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.waypoints_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ProtoAction::_internal_mutable_waypoints() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.waypoints_;
}

// string material = 5;
inline void ProtoAction::clear_material() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.material_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& ProtoAction::material() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.material)
  return _internal_material();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoAction::set_material(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.material_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoAction.material)
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::mutable_material()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_material();
  // @@protoc_insertion_point(field_mutable:athena.ProtoAction.material)
  return _s;
}
inline const ::std::string& ProtoAction::_internal_material() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.material_.Get();
}
inline void ProtoAction::_internal_set_material(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.material_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::_internal_mutable_material() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.material_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoAction::release_material() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoAction.material)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.material_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.material_.Set("", GetArena());
  }
  return released;
}
inline void ProtoAction::set_allocated_material(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.material_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.material_.IsDefault()) {
    _impl_.material_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoAction.material)
}

// repeated int32 parents = 6;
inline int ProtoAction::_internal_parents_size() const {
  return _internal_parents().size();
}
inline int ProtoAction::parents_size() const {
  return _internal_parents_size();
}
inline void ProtoAction::clear_parents() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parents_.Clear();
}
inline ::int32_t ProtoAction::parents(int index) const {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.parents)
  return _internal_parents().Get(index);
}
inline void ProtoAction::set_parents(int index, ::int32_t value) {
  _internal_mutable_parents()->Set(index, value);
  // @@protoc_insertion_point(field_set:athena.ProtoAction.parents)
}
inline void ProtoAction::add_parents(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_parents()->Add(value);
  // @@protoc_insertion_point(field_add:athena.ProtoAction.parents)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& ProtoAction::parents() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoAction.parents)
  return _internal_parents();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL ProtoAction::mutable_parents()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoAction.parents)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_parents();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
ProtoAction::_internal_parents() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parents_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
ProtoAction::_internal_mutable_parents() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.parents_;
}

// repeated string preconditions = 7;
inline int ProtoAction::_internal_preconditions_size() const {
  return _internal_preconditions().size();
}
inline int ProtoAction::preconditions_size() const {
  return _internal_preconditions_size();
}
inline void ProtoAction::clear_preconditions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.preconditions_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::add_preconditions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_preconditions()->Add();
  // @@protoc_insertion_point(field_add_mutable:athena.ProtoAction.preconditions)
  return _s;
}
inline const ::std::string& ProtoAction::preconditions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.preconditions)
  return _internal_preconditions().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::mutable_preconditions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:athena.ProtoAction.preconditions)
  return _internal_mutable_preconditions()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ProtoAction::set_preconditions(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_preconditions()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:athena.ProtoAction.preconditions)
}
template <typename Arg_, typename... Args_>
inline void ProtoAction::add_preconditions(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_preconditions(),
                               ::std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:athena.ProtoAction.preconditions)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& ProtoAction::preconditions()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoAction.preconditions)
  return _internal_preconditions();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ProtoAction::mutable_preconditions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoAction.preconditions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_preconditions();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
ProtoAction::_internal_preconditions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.preconditions_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ProtoAction::_internal_mutable_preconditions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.preconditions_;
}

// repeated string effects = 8;
inline int ProtoAction::_internal_effects_size() const {
  return _internal_effects().size();
}
inline int ProtoAction::effects_size() const {
  return _internal_effects_size();
}
inline void ProtoAction::clear_effects() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.effects_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::add_effects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_effects()->Add();
  // @@protoc_insertion_point(field_add_mutable:athena.ProtoAction.effects)
  return _s;
}
inline const ::std::string& ProtoAction::effects(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoAction.effects)
  return _internal_effects().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL ProtoAction::mutable_effects(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:athena.ProtoAction.effects)
  return _internal_mutable_effects()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ProtoAction::set_effects(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_effects()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:athena.ProtoAction.effects)
}
template <typename Arg_, typename... Args_>
inline void ProtoAction::add_effects(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_effects(),
                               ::std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:athena.ProtoAction.effects)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& ProtoAction::effects()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoAction.effects)
  return _internal_effects();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ProtoAction::mutable_effects() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoAction.effects)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_effects();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
ProtoAction::_internal_effects() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.effects_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ProtoAction::_internal_mutable_effects() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.effects_;
}

// -------------------------------------------------------------------

// ProtoMethod

// string name = 1;
inline void ProtoMethod::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ProtoMethod::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoMethod.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoMethod::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoMethod.name)
}
inline ::std::string* PROTOBUF_NONNULL ProtoMethod::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:athena.ProtoMethod.name)
  return _s;
}
inline const ::std::string& ProtoMethod::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void ProtoMethod::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoMethod::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoMethod::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoMethod.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void ProtoMethod::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoMethod.name)
}

// int32 id = 2;
inline void ProtoMethod::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t ProtoMethod::id() const {
  // @@protoc_insertion_point(field_get:athena.ProtoMethod.id)
  return _internal_id();
}
inline void ProtoMethod::set_id(::int32_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:athena.ProtoMethod.id)
}
inline ::int32_t ProtoMethod::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void ProtoMethod::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string robot = 3;
inline void ProtoMethod::clear_robot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& ProtoMethod::robot() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoMethod.robot)
  return _internal_robot();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProtoMethod::set_robot(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.robot_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:athena.ProtoMethod.robot)
}
inline ::std::string* PROTOBUF_NONNULL ProtoMethod::mutable_robot()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_robot();
  // @@protoc_insertion_point(field_mutable:athena.ProtoMethod.robot)
  return _s;
}
inline const ::std::string& ProtoMethod::_internal_robot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.robot_.Get();
}
inline void ProtoMethod::_internal_set_robot(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.robot_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProtoMethod::_internal_mutable_robot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.robot_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProtoMethod::release_robot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:athena.ProtoMethod.robot)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.robot_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.robot_.Set("", GetArena());
  }
  return released;
}
inline void ProtoMethod::set_allocated_robot(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.robot_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.robot_.IsDefault()) {
    _impl_.robot_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:athena.ProtoMethod.robot)
}

// repeated int32 parents = 4;
inline int ProtoMethod::_internal_parents_size() const {
  return _internal_parents().size();
}
inline int ProtoMethod::parents_size() const {
  return _internal_parents_size();
}
inline void ProtoMethod::clear_parents() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parents_.Clear();
}
inline ::int32_t ProtoMethod::parents(int index) const {
  // @@protoc_insertion_point(field_get:athena.ProtoMethod.parents)
  return _internal_parents().Get(index);
}
inline void ProtoMethod::set_parents(int index, ::int32_t value) {
  _internal_mutable_parents()->Set(index, value);
  // @@protoc_insertion_point(field_set:athena.ProtoMethod.parents)
}
inline void ProtoMethod::add_parents(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_parents()->Add(value);
  // @@protoc_insertion_point(field_add:athena.ProtoMethod.parents)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& ProtoMethod::parents() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoMethod.parents)
  return _internal_parents();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL ProtoMethod::mutable_parents()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoMethod.parents)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_parents();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
ProtoMethod::_internal_parents() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parents_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
ProtoMethod::_internal_mutable_parents() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.parents_;
}

// repeated int32 actions_ids = 5;
inline int ProtoMethod::_internal_actions_ids_size() const {
  return _internal_actions_ids().size();
}
inline int ProtoMethod::actions_ids_size() const {
  return _internal_actions_ids_size();
}
inline void ProtoMethod::clear_actions_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actions_ids_.Clear();
}
inline ::int32_t ProtoMethod::actions_ids(int index) const {
  // @@protoc_insertion_point(field_get:athena.ProtoMethod.actions_ids)
  return _internal_actions_ids().Get(index);
}
inline void ProtoMethod::set_actions_ids(int index, ::int32_t value) {
  _internal_mutable_actions_ids()->Set(index, value);
  // @@protoc_insertion_point(field_set:athena.ProtoMethod.actions_ids)
}
inline void ProtoMethod::add_actions_ids(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_actions_ids()->Add(value);
  // @@protoc_insertion_point(field_add:athena.ProtoMethod.actions_ids)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& ProtoMethod::actions_ids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoMethod.actions_ids)
  return _internal_actions_ids();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL ProtoMethod::mutable_actions_ids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoMethod.actions_ids)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_actions_ids();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
ProtoMethod::_internal_actions_ids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.actions_ids_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
ProtoMethod::_internal_mutable_actions_ids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.actions_ids_;
}

// -------------------------------------------------------------------

// ProtoExecutionPlan

// repeated .athena.ProtoAction action = 1;
inline int ProtoExecutionPlan::_internal_action_size() const {
  return _internal_action().size();
}
inline int ProtoExecutionPlan::action_size() const {
  return _internal_action_size();
}
inline void ProtoExecutionPlan::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_.Clear();
}
inline ::athena::ProtoAction* PROTOBUF_NONNULL ProtoExecutionPlan::mutable_action(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:athena.ProtoExecutionPlan.action)
  return _internal_mutable_action()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>* PROTOBUF_NONNULL ProtoExecutionPlan::mutable_action()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoExecutionPlan.action)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_action();
}
inline const ::athena::ProtoAction& ProtoExecutionPlan::action(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoExecutionPlan.action)
  return _internal_action().Get(index);
}
inline ::athena::ProtoAction* PROTOBUF_NONNULL ProtoExecutionPlan::add_action()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::athena::ProtoAction* _add = _internal_mutable_action()->Add();
  // @@protoc_insertion_point(field_add:athena.ProtoExecutionPlan.action)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>& ProtoExecutionPlan::action() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoExecutionPlan.action)
  return _internal_action();
}
inline const ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>&
ProtoExecutionPlan::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.action_;
}
inline ::google::protobuf::RepeatedPtrField<::athena::ProtoAction>* PROTOBUF_NONNULL
ProtoExecutionPlan::_internal_mutable_action() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.action_;
}

// repeated .athena.ProtoMethod method = 2;
inline int ProtoExecutionPlan::_internal_method_size() const {
  return _internal_method().size();
}
inline int ProtoExecutionPlan::method_size() const {
  return _internal_method_size();
}
inline void ProtoExecutionPlan::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_.Clear();
}
inline ::athena::ProtoMethod* PROTOBUF_NONNULL ProtoExecutionPlan::mutable_method(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:athena.ProtoExecutionPlan.method)
  return _internal_mutable_method()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>* PROTOBUF_NONNULL ProtoExecutionPlan::mutable_method()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:athena.ProtoExecutionPlan.method)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_method();
}
inline const ::athena::ProtoMethod& ProtoExecutionPlan::method(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:athena.ProtoExecutionPlan.method)
  return _internal_method().Get(index);
}
inline ::athena::ProtoMethod* PROTOBUF_NONNULL ProtoExecutionPlan::add_method()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::athena::ProtoMethod* _add = _internal_mutable_method()->Add();
  // @@protoc_insertion_point(field_add:athena.ProtoExecutionPlan.method)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>& ProtoExecutionPlan::method() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:athena.ProtoExecutionPlan.method)
  return _internal_method();
}
inline const ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>&
ProtoExecutionPlan::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_;
}
inline ::google::protobuf::RepeatedPtrField<::athena::ProtoMethod>* PROTOBUF_NONNULL
ProtoExecutionPlan::_internal_mutable_method() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.method_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace athena


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // executionplan_2eproto_2epb_2eh
