(define (problem contruction_site_pb1)
(:domain contruction_site)
(:requirements)
(:objects 
  rb1 - MACHINE
  rb2 - MACHINE
  mat1 - LOADABLE_MATERIAL
  mat2 - LOADABLE_MATERIAL
  parkingarea1 - LOCATION
  parkingarea2 - LOCATION
  wp1 - LOCATION
  wp2 - LOCATION
  wp3 - LOCATION
  wp4 - LOCATION
  wp5 - LOCATION
  wp6 - LOCATION
  wp7 - LOCATION
  wp8 - LOCATION
  wp9 - LOCATION
  wp10 - LOCATION
  wp11 - LOCATION
  wp12 - LOCATION
)
(:initialization
  (pile mat1)
  (pile mat2)
  (at mat1 wp9)
  (at mat2 wp10)
  (= (material_amount_at_location mat1 parkingarea1) 0.0)
  (= (material_amount_at_location mat1 parkingarea2) 0.0)
  (= (material_amount_at_location mat1 wp1) 0.0)
  (= (material_amount_at_location mat1 wp2) 0.0)
  (= (material_amount_at_location mat1 wp3) 0.0)
  (= (material_amount_at_location mat1 wp4) 0.0)
  (= (material_amount_at_location mat1 wp5) 0.0)
  (= (material_amount_at_location mat1 wp6) 0.0)
  (= (material_amount_at_location mat1 wp7) 0.0)
  (= (material_amount_at_location mat1 wp8) 0.0)
  (= (material_amount_at_location mat1 wp9) 5.0)
  (= (material_amount_at_location mat1 wp10) 0.0)
  (= (material_amount_at_location mat1 wp11) 0.0)
  (= (material_amount_at_location mat1 wp12) 0.0)
  (= (material_amount_at_location mat2 parkingarea1) 0.0)
  (= (material_amount_at_location mat2 parkingarea2) 0.0)
  (= (material_amount_at_location mat2 wp1) 0.0)
  (= (material_amount_at_location mat2 wp2) 0.0)
  (= (material_amount_at_location mat2 wp3) 0.0)
  (= (material_amount_at_location mat2 wp4) 0.0)
  (= (material_amount_at_location mat2 wp5) 0.0)
  (= (material_amount_at_location mat2 wp6) 0.0)
  (= (material_amount_at_location mat2 wp7) 0.0)
  (= (material_amount_at_location mat2 wp8) 0.0)
  (= (material_amount_at_location mat2 wp9) 0.0)
  (= (material_amount_at_location mat2 wp10) 5.0)
  (= (material_amount_at_location mat2 wp11) 0.0)
  (= (material_amount_at_location mat2 wp12) 0.0)
  (= (total_cost) 0.0)
  (wheelloader rb1)
  (wheelloader rb2)
  (can_load rb1)
  (can_load rb2)
  (idle rb1)
  (idle rb2)
  (at rb1 parkingarea1)
  (at rb2 parkingarea2)
  (armlow rb1)
  (armlow rb2)
  (clear wp1)
  (clear wp2)
  (clear wp3)
  (clear wp4)
  (clear wp5)
  (clear wp6)
  (clear wp7)
  (clear wp8)
  (clear wp11)
  (clear wp12)
  (nomachineatlocation wp1)
  (nomachineatlocation wp2)
  (nomachineatlocation wp3)
  (nomachineatlocation wp4)
  (nomachineatlocation wp5)
  (nomachineatlocation wp6)
  (nomachineatlocation wp7)
  (nomachineatlocation wp8)
  (nomachineatlocation wp9)
  (nomachineatlocation wp10)
  (nomachineatlocation wp11)
  (nomachineatlocation wp12)
  (clear_path parkingarea1 wp1)
  (clear_path parkingarea1 wp2)
  (clear_path parkingarea1 wp3)
  (clear_path parkingarea1 wp4)
  (clear_path parkingarea1 wp5)
  (clear_path parkingarea1 wp6)
  (clear_path parkingarea1 wp7)
  (clear_path parkingarea1 wp8)
  (clear_path parkingarea1 wp9)
  (clear_path parkingarea1 wp10)
  (clear_path parkingarea1 wp11)
  (clear_path parkingarea1 wp12)
  (clear_path parkingarea2 wp1)
  (clear_path parkingarea2 wp2)
  (clear_path parkingarea2 wp3)
  (clear_path parkingarea2 wp4)
  (clear_path parkingarea2 wp5)
  (clear_path parkingarea2 wp6)
  (clear_path parkingarea2 wp7)
  (clear_path parkingarea2 wp8)
  (clear_path parkingarea2 wp9)
  (clear_path parkingarea2 wp10)
  (clear_path parkingarea2 wp11)
  (clear_path parkingarea2 wp12)
  (clear_path wp1 wp2)
  (clear_path wp1 wp3)
  (clear_path wp1 wp4)
  (clear_path wp1 wp5)
  (clear_path wp1 wp6)
  (clear_path wp1 wp7)
  (clear_path wp1 wp8)
  (clear_path wp1 wp9)
  (clear_path wp1 wp10)
  (clear_path wp1 wp11)
  (clear_path wp1 wp12)
  (clear_path wp2 wp1)
  (clear_path wp2 wp3)
  (clear_path wp2 wp4)
  (clear_path wp2 wp5)
  (clear_path wp2 wp6)
  (clear_path wp2 wp7)
  (clear_path wp2 wp8)
  (clear_path wp2 wp9)
  (clear_path wp2 wp10)
  (clear_path wp2 wp11)
  (clear_path wp2 wp12)
  (clear_path wp3 wp1)
  (clear_path wp3 wp2)
  (clear_path wp3 wp4)
  (clear_path wp3 wp5)
  (clear_path wp3 wp6)
  (clear_path wp3 wp7)
  (clear_path wp3 wp8)
  (clear_path wp3 wp9)
  (clear_path wp3 wp10)
  (clear_path wp3 wp11)
  (clear_path wp3 wp12)
  (clear_path wp4 wp1)
  (clear_path wp4 wp2)
  (clear_path wp4 wp3)
  (clear_path wp4 wp5)
  (clear_path wp4 wp6)
  (clear_path wp4 wp7)
  (clear_path wp4 wp8)
  (clear_path wp4 wp9)
  (clear_path wp4 wp10)
  (clear_path wp4 wp11)
  (clear_path wp4 wp12)
  (clear_path wp5 wp1)
  (clear_path wp5 wp2)
  (clear_path wp5 wp3)
  (clear_path wp5 wp4)
  (clear_path wp5 wp6)
  (clear_path wp5 wp7)
  (clear_path wp5 wp8)
  (clear_path wp5 wp9)
  (clear_path wp5 wp10)
  (clear_path wp5 wp11)
  (clear_path wp5 wp12)
  (clear_path wp6 wp1)
  (clear_path wp6 wp2)
  (clear_path wp6 wp3)
  (clear_path wp6 wp4)
  (clear_path wp6 wp5)
  (clear_path wp6 wp7)
  (clear_path wp6 wp8)
  (clear_path wp6 wp9)
  (clear_path wp6 wp10)
  (clear_path wp6 wp11)
  (clear_path wp6 wp12)
  (clear_path wp7 wp1)
  (clear_path wp7 wp2)
  (clear_path wp7 wp3)
  (clear_path wp7 wp4)
  (clear_path wp7 wp5)
  (clear_path wp7 wp6)
  (clear_path wp7 wp8)
  (clear_path wp7 wp9)
  (clear_path wp7 wp10)
  (clear_path wp7 wp11)
  (clear_path wp7 wp12)
  (clear_path wp8 wp1)
  (clear_path wp8 wp2)
  (clear_path wp8 wp3)
  (clear_path wp8 wp4)
  (clear_path wp8 wp5)
  (clear_path wp8 wp6)
  (clear_path wp8 wp7)
  (clear_path wp8 wp9)
  (clear_path wp8 wp10)
  (clear_path wp8 wp11)
  (clear_path wp8 wp12)
  (clear_path wp9 wp1)
  (clear_path wp9 wp2)
  (clear_path wp9 wp3)
  (clear_path wp9 wp4)
  (clear_path wp9 wp5)
  (clear_path wp9 wp6)
  (clear_path wp9 wp7)
  (clear_path wp9 wp8)
  (clear_path wp9 wp10)
  (clear_path wp9 wp11)
  (clear_path wp9 wp12)
  (clear_path wp10 wp1)
  (clear_path wp10 wp2)
  (clear_path wp10 wp3)
  (clear_path wp10 wp4)
  (clear_path wp10 wp5)
  (clear_path wp10 wp6)
  (clear_path wp10 wp7)
  (clear_path wp10 wp8)
  (clear_path wp10 wp9)
  (clear_path wp10 wp11)
  (clear_path wp10 wp12)
  (clear_path wp11 wp1)
  (clear_path wp11 wp2)
  (clear_path wp11 wp3)
  (clear_path wp11 wp4)
  (clear_path wp11 wp5)
  (clear_path wp11 wp6)
  (clear_path wp11 wp7)
  (clear_path wp11 wp8)
  (clear_path wp11 wp9)
  (clear_path wp11 wp10)
  (clear_path wp11 wp12)
  (clear_path wp12 wp1)
  (clear_path wp12 wp2)
  (clear_path wp12 wp3)
  (clear_path wp12 wp4)
  (clear_path wp12 wp5)
  (clear_path wp12 wp6)
  (clear_path wp12 wp7)
  (clear_path wp12 wp8)
  (clear_path wp12 wp9)
  (clear_path wp12 wp10)
  (clear_path wp12 wp11)
)

)
(:goal   (and (at mat1 wp7)
  (at mat2 wp5)))
)

