#ifndef PLAN2_PROTOBUF__EXECUTION_PLAN_HPP
#define PLAN2_PROTOBUF__EXECUTION_PLAN_HPP

#include <iostream>
#include <string>
#include <fstream>

#include "plan2_protobuf/executionplan.pb.h"
#include "plan2_protobuf/action.hpp"


namespace planning2{


class Plan 
{
public:   

    /**
     * @brief Iterates though all the actions in the ExecutionPlan
     * 
     * @param execution_plan the data file that contains the execution plan.
     */
    std::vector<planning2::Action> GetActions(const ExecutionPlan& execution_plan);

    /**
     * @brief Parse  the dataFile computed by java
     * 
     * @param file the name of the data file generated by java
     * @return The parsed execution plan  
     */
    ExecutionPlan ParseFile(std::string file);

}; //End Class
}  //namespace planning2


#endif // PLAN2_PROTOBUF__EXECUTION_PLAN_HPP
